github: chandril-mallick
buy_me_a_coffee: chandril mallick
patreon: chandrilmallick
ko_fi: chandrilmallick
custom: ["https://abouttech.co.in/support", "https://smartsant-iot---early-disease-prediction-system.streamlit.app/"]
